### ISSUE TITLE
OS X compilation error

### ISSUE THREAD

**Issue by renatosc** [davidalbertonogueira/MLP#13]
I tried to compile the project, but **make** fails with the following error:

`Compiling program NodeTest
g++  src/NodeTest.o src/MLP.o -std=gnu++11 -std=c++11 -Wall -fmessage-length=0 -fPIC -I./deps -I   -g3 -L  -v -o NodeTest
ld: warning: directory not found for option '-L-v'
Creating static lib mlp.a
ar rcs mlp.a ./src/MLP.o
Creating dynamic lib mlp.so
g++ -o mlp.so ./src/MLP.o -shared -L  -v 
ld: warning: directory not found for option '-L-v'
Undefined symbols for architecture x86_64:
  "el::base::utils::s_currentHost", referenced from:
      el::base::LogFormat::updateFormatSpec() in MLP.o
  "el::base::utils::s_currentUser", referenced from:
      el::base::LogFormat::updateFormatSpec() in MLP.o
  "el::base::elStorage", referenced from:
      el::base::Writer::construct(int, char const*, ...) in MLP.o
      el::base::Writer::initializeLogger(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool) in MLP.o
      el::base::MessageBuilder::initialize(el::Logger*) in MLP.o
      el::base::MessageBuilder::operator<<(char const*) in MLP.o
      el::base::Writer::processDispatch() in MLP.o
      el::base::Writer::triggerDispatch() in MLP.o
      el::base::LogDispatcher::dispatch() in MLP.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mlp.so] Error 1`

any idea what might be? maybe a required missing dependency?

Thanks.

**Comment by davidalbertonogueira** [comment]
Thank you for your interest, but macOS is not officially supported, and I don't have a way to test in it. 
If you manage to fix it for macOS, I would much appreciate your contribution with a pull request.

**Comment by renatosc** [comment]
Did you take a look in the log? Any ideas about the complain of "el::base::utils::s_currentHost" not being defined? Is that variable familiar to you?

**Comment by davidalbertonogueira** [comment]
Searching in the project, It is a variable in the external logging library that I'm using (I assume it is not supported in macOS) -> deps/easylogging++.h

**Comment by renatosc** [comment]
Ok. Let me check how can I take of care of that.

**Comment by smiranda** [comment]
@davidalbertonogueira since you already depend on microunit you could consider using the logging macros available there 👺
