### ISSUE TITLE
What are the possible activation functions?

### ISSUE THREAD

**Issue by alexandretok** [davidalbertonogueira/MLP#2]
In your example you use "sigmoid" and "linear".

Are there any other type of function that I can use?

Thanks!

**Comment by davidalbertonogueira** [comment]
The library has sigmoid, tanh and linear defined (check [Utils.h#L88](https://github.com/davidalbertonogueira/MLP/blob/0a636416ed9e597b6169a9e1d1127d035c96df6e/src/Utils.h#L88) ).
The library is very extensible and easy to hack. If you want/need another one, it can easily be added by appending that new activation function and its derivative function to that header file and "registering" the pair in the ActivationFunctionsManager constructor.

**Comment by alexandretok** [comment]
Thanks!
