### ISSUE TITLE
how i can add hidden layer ?

### ISSUE THREAD

**Issue by eSkry** [davidalbertonogueira/MLP#5]
Hello (sorry my English), i wont create neural web with 3 hidden layers, i am write this: (3 input, two layers on 3 neurons, and 2 output).

    mWeb = new MLP({ 3, 3, 3, 2 }, { "sigmoid", "linear" }, false);
    std::vector<TrainingSample> traning_sample = {
			{{1, 0, 0}, {1, 0}},
			{{0, 1, 0}, {1, 1}},
			{{0, 1, 1}, {0, 0}}
    };
    mWeb->Train(traning_sample, 0.01, 5000, 0.10, false);

it's correct? i have errors with this code (time out).
if it is not correct, please, write me correct realization.

if i am write this:

    mWeb = new MLP({ 3, 3, 2 }, { "sigmoid", "linear" }, false);
    std::vector<TrainingSample> traning_sample = {
			{{1, 0, 0}, {1, 0}},
			{{0, 1, 0}, {1, 1}},
			{{0, 1, 1}, {0, 0}}
    };
    mWeb->Train(traning_sample, 0.01, 5000, 0.10, false);

is works ok.

**Comment by davidalbertonogueira** [comment]
If you have 3 hidden layers, you have to specify a vector with 3 activation functions as the second argument in the constructor, like: 

`mWeb = new MLP({ 3, 3, 3, 2 }, { "sigmoid", "sigmoid", "linear" }, false);`

**Comment by eSkry** [comment]
thanks 👍 it very good library.

**Comment by davidalbertonogueira** [comment]
You're welcome.

**Comment by davidalbertonogueira** [comment]
If your use case is open-source, feel free to ask for a pull request of your train/test source file and your dataset (reporting your accuracy score).


________________________________
De: eSkry <notifications@github.com>
Enviado: Monday, April 2, 2018 12:34:06 PM
Para: davidalbertonogueira/MLP
Cc: David Nogueira; Comment
Assunto: Re: [davidalbertonogueira/MLP] how i can add hidden layer ? (#5)


thanks 👍 it very good library.
