### ISSUE TITLE
Chrono.h file not found in Utils.h file

### ISSUE THREAD

**Issue by rlunaro** [davidalbertonogueira/MLP#6]
Hello; 

I've downloaded your project and I am trying to build the example: I've found that in the file "Utils.h" appears a reference to a include file called Crono.h that doesn't appear.

**Comment by davidalbertonogueira** [comment]
You have the file there:

https://github.com/davidalbertonogueira/MLP/blob/master/deps/Chrono.h

Are you using the provided makefile?


From: Raul Luna Rodríguez
Sent: Saturday, April 21, 21:52
Subject: [davidalbertonogueira/MLP] Chrono.h file not found in Utils.h file (#6)
To: davidalbertonogueira/MLP
Cc: Subscribed


Hello;
I've downloaded your project and I am trying to build the example: I've found that in the file "Utils.h" appears a reference to a include file called Crono.h that doesn't appear.
